// mobile/src/components/AppTabBar.tsx
import { colors } from "@/lib/colors";
import { tapHaptic } from "@/lib/haptics";
import { BookOpen, CalendarDays, House, Plus, ShoppingCart } from "lucide-react-native";
import { useEffect, useState } from "react";
import { Animated, Pressable, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { Text } from "./ui/text";

/**
 * Structural subset of react-navigation's BottomTabBarProps — expo-router
 * SDK 57 vendors its own react-navigation copy, so importing the type from
 * @react-navigation/bottom-tabs would clash with the vendored one.
 */
interface TabBarProps {
  state: { index: number; routes: { key: string; name: string }[] };
  navigation: {
    emit: (event: {
      type: "tabPress";
      target: string;
      canPreventDefault: true;
    }) => { defaultPrevented: boolean };
    navigate: (name: string) => void;
  };
}

const TAB_META: Record<string, { label: string; Icon: typeof House }> = {
  home: { label: "Home", Icon: House },
  recipes: { label: "Recipes", Icon: BookOpen },
  planner: { label: "Planner", Icon: CalendarDays },
  list: { label: "Grocery", Icon: ShoppingCart }
};

/**
 * Custom bottom tab bar: 4 tabs with a raised green "+" in the middle
 * (opens the Add sheet) — mirrors the web AppTabBar.
 */
export function AppTabBar({
  state,
  navigation,
  addOpen,
  onAddPress
}: TabBarProps & { addOpen: boolean; onAddPress: () => void }) {
  const insets = useSafeAreaInsets();
  const [rotation] = useState(() => new Animated.Value(0));

  useEffect(() => {
    Animated.timing(rotation, {
      toValue: addOpen ? 1 : 0,
      duration: 180,
      useNativeDriver: true
    }).start();
  }, [addOpen, rotation]);

  const rotate = rotation.interpolate({ inputRange: [0, 1], outputRange: ["0deg", "45deg"] });

  const pressTab = (index: number) => {
    const route = state.routes[index]!;
    const focused = state.index === index;
    tapHaptic();
    const event = navigation.emit({
      type: "tabPress",
      target: route.key,
      canPreventDefault: true
    });
    if (!focused && !event.defaultPrevented) navigation.navigate(route.name);
  };

  const renderTab = (index: number) => {
    const route = state.routes[index]!;
    const meta = TAB_META[route.name] ?? { label: route.name, Icon: House };
    const focused = state.index === index;
    const color = focused ? colors.green500 : colors.faint;
    return (
      <Pressable
        key={route.key}
        accessibilityRole="tab"
        accessibilityState={{ selected: focused }}
        accessibilityLabel={meta.label}
        onPress={() => pressTab(index)}
        className="flex-1 items-center justify-center gap-1"
      >
        <meta.Icon size={22} color={color} strokeWidth={focused ? 2.2 : 1.8} />
        <Text
          className={focused ? "text-[11px] text-[#22c55e] font-sans-medium" : "text-[11px] text-faint"}
        >
          {meta.label}
        </Text>
      </Pressable>
    );
  };

  return (
    <View
      className="border-t border-border bg-background"
      style={{ paddingBottom: insets.bottom }}
    >
      <View className="h-16 flex-row items-stretch">
        {renderTab(0)}
        {renderTab(1)}
        <View className="flex-1 items-center">
          <Pressable
            accessibilityRole="button"
            accessibilityLabel={addOpen ? "Close add menu" : "Add"}
            onPress={() => {
              tapHaptic();
              onAddPress();
            }}
            className="-mt-5 h-14 w-14 items-center justify-center rounded-full bg-primary shadow-lg active:opacity-90"
          >
            <Animated.View style={{ transform: [{ rotate }] }}>
              <Plus size={26} color={colors.foreground} strokeWidth={2.4} />
            </Animated.View>
          </Pressable>
        </View>
        {renderTab(2)}
        {renderTab(3)}
      </View>
    </View>
  );
}

// src/components/AppTabBar.vue
<script setup lang="ts">
import { cn } from "@/lib/utils";
import { tabByRouteName, tabs, type SiteRouteName, type TabId } from "@/sitemap";
import { BookOpen, CalendarDays, Home, Plus, ShoppingCart } from "@lucide/vue";
import { computed } from "vue";
import { useRoute, useRouter } from "vue-router";

const open = defineModel<boolean>("open", { default: false });

const route = useRoute();
const router = useRouter();

const activeTab = computed<TabId | undefined>(() => {
  if (open.value) return "add";
  return tabByRouteName[route.name as SiteRouteName];
});

const icons: Record<TabId, typeof Home> = {
  home: Home,
  recipes: BookOpen,
  add: Plus,
  planner: CalendarDays,
  list: ShoppingCart
};

function onTab(id: TabId) {
  if (id === "add") {
    open.value = !open.value;
    return;
  }
  open.value = false;
  const tab = tabs.find((t) => t.id === id);
  if (tab?.path) router.push(tab.path);
}
</script>

<template>
  <nav
    class="fixed bottom-0 left-1/2 z-[60] w-full max-w-md -translate-x-1/2 border-t border-border bg-elevated px-2 pt-2 pb-[calc(0.75rem+env(safe-area-inset-bottom))]"
    aria-label="Primary"
  >
    <div class="grid grid-cols-5 items-end">
      <button
        v-for="tab in tabs"
        :key="tab.id"
        type="button"
        class="flex flex-col items-center gap-0.5 outline-none"
        :class="tab.id === 'add' ? '' : 'py-0.5'"
        :aria-current="activeTab === tab.id ? 'page' : undefined"
        @click="onTab(tab.id)"
      >
        <template v-if="tab.id === 'add'">
          <span
            class="flex size-[50px] -mt-7 items-center justify-center rounded-full border-4 border-background bg-primary text-primary-foreground shadow-[0_4px_12px_rgba(22,163,74,0.4)] transition-transform duration-200"
            :class="open ? 'rotate-45' : ''"
          >
            <Plus class="size-[22px]" :stroke-width="2.5" />
          </span>
          <span class="mt-0.5 text-[10px] font-medium text-muted-foreground">
            {{ open ? "Close" : tab.label }}
          </span>
        </template>
        <template v-else>
          <component
            :is="icons[tab.id]"
            class="size-[21px] transition-colors"
            :class="activeTab === tab.id ? 'text-[#22c55e]' : 'text-muted-foreground'"
            :stroke-width="2"
          />
          <span
            :class="
              cn(
                'text-[10px] transition-colors',
                activeTab === tab.id
                  ? 'font-semibold text-[#22c55e]'
                  : 'font-medium text-muted-foreground'
              )
            "
          >
            {{ tab.label }}
          </span>
        </template>
      </button>
    </div>
  </nav>
</template>
