// mobile/src/components/HomeWeekStrip.tsx
import { addDays, startOfDay, startOfWeekMonday, toDateKey } from "@/lib/dates";
import { tapHaptic } from "@/lib/haptics";
import { useCallback, useEffect, useLayoutEffect, useMemo, useRef, useState } from "react";
import { Animated, Easing, PanResponder, Pressable, View } from "react-native";
import { Text } from "./ui/text";

const DAY_LABELS = ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"];
const SWIPE_THRESHOLD_RATIO = 0.22;
const SWIPE_VELOCITY = 0.4;
const SNAP_MS = 280;

/**
 * Swipeable 3-panel week selector (prev / current / next) with planned-day
 * dots — port of the web HomeWeekStrip.
 */
export function HomeWeekStrip({
  plannedKeys,
  onWeekChange,
  onSelectDay
}: {
  plannedKeys: Set<string>;
  /** Fired with the center week, plus a range covering prev/current/next for dots. */
  onWeekChange: (weekStart: Date, weekDays: Date[], rangeStart: Date, rangeEnd: Date) => void;
  onSelectDay: (date: Date) => void;
}) {
  const today = useMemo(() => startOfDay(), []);
  const thisWeekStart = useMemo(() => startOfWeekMonday(today), [today]);
  const todayKey = toDateKey(today);

  const [width, setWidth] = useState(0);
  const [weekOffset, setWeekOffset] = useState(0);
  const [translateX] = useState(() => new Animated.Value(0));
  const widthRef = useRef(0);
  const animatingRef = useRef(false);
  const dragStart = useRef(0);

  const daysForOffset = useCallback(
    (offset: number): Date[] => {
      const start = addDays(thisWeekStart, offset * 7);
      return Array.from({ length: 7 }, (_, i) => addDays(start, i));
    },
    [thisWeekStart]
  );

  const panels = useMemo(
    () => [
      { offset: weekOffset - 1, days: daysForOffset(weekOffset - 1) },
      { offset: weekOffset, days: daysForOffset(weekOffset) },
      { offset: weekOffset + 1, days: daysForOffset(weekOffset + 1) }
    ],
    [weekOffset, daysForOffset]
  );

  const weekLabel = useMemo(() => {
    if (weekOffset === 0) return "This week";
    if (weekOffset === -1) return "Last week";
    if (weekOffset === 1) return "Next week";
    const start = addDays(thisWeekStart, weekOffset * 7);
    const end = addDays(start, 6);
    const opts: Intl.DateTimeFormatOptions = { month: "short", day: "numeric" };
    return `${start.toLocaleDateString(undefined, opts)} – ${end.toLocaleDateString(undefined, opts)}`;
  }, [weekOffset, thisWeekStart]);

  // Notify parent of the visible week + prefetch range (prev/current/next).
  useEffect(() => {
    const start = addDays(thisWeekStart, weekOffset * 7);
    onWeekChange(start, daysForOffset(weekOffset), addDays(start, -7), addDays(start, 13));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [weekOffset, thisWeekStart]);

  // Keep the track resting on the center panel whenever layout or week changes.
  useLayoutEffect(() => {
    widthRef.current = width;
    translateX.setValue(-width);
  }, [width, weekOffset, translateX]);

  const snapTo = useCallback(
    (delta: -1 | 0 | 1) => {
      const w = widthRef.current;
      if (!w) return;
      animatingRef.current = true;
      const target = delta === 0 ? -w : delta < 0 ? 0 : -w * 2;
      Animated.timing(translateX, {
        toValue: target,
        duration: SNAP_MS,
        easing: Easing.bezier(0.22, 1, 0.36, 1),
        useNativeDriver: true
      }).start(({ finished }) => {
        animatingRef.current = false;
        if (delta !== 0 && finished) {
          setWeekOffset((w0) => w0 + delta);
        } else {
          translateX.setValue(-widthRef.current);
        }
      });
    },
    [translateX]
  );
  const snapToRef = useRef(snapTo);
  useEffect(() => {
    snapToRef.current = snapTo;
  }, [snapTo]);

  // PanResponder.create only stores these callbacks; they run on gesture
  // events, never during render, so the refs rule is a false positive here.
  const panResponder = useMemo(
    () =>
      // eslint-disable-next-line react-hooks/refs
      PanResponder.create({
        onMoveShouldSetPanResponder: (_e, g) =>
          !animatingRef.current && Math.abs(g.dx) > 8 && Math.abs(g.dx) > Math.abs(g.dy),
        onPanResponderGrant: () => {
          dragStart.current = -widthRef.current;
        },
        onPanResponderMove: (_e, g) => {
          translateX.setValue(dragStart.current + g.dx);
        },
        onPanResponderRelease: (_e, g) => {
          const w = widthRef.current || 1;
          const commit =
            Math.abs(g.dx) >= w * SWIPE_THRESHOLD_RATIO || Math.abs(g.vx) >= SWIPE_VELOCITY;
          if (commit) snapToRef.current(g.dx < 0 ? 1 : -1);
          else snapToRef.current(0);
        },
        onPanResponderTerminate: () => snapToRef.current(0)
      }),
    [translateX]
  );

  const goToThisWeek = () => {
    if (weekOffset === 0) return;
    if (Math.abs(weekOffset) === 1) {
      snapTo(weekOffset > 0 ? -1 : 1);
    } else {
      setWeekOffset(0);
    }
  };

  return (
    <View>
      <View className="mb-2 flex-row items-center justify-between gap-2">
        <Text className="font-sans-semibold text-xs text-muted-foreground">{weekLabel}</Text>
        {weekOffset !== 0 ? (
          <Pressable onPress={goToThisWeek} hitSlop={8} className="active:opacity-70">
            <Text className="font-sans-semibold text-[11.5px] text-[#22c55e]">
              Jump to this week
            </Text>
          </Pressable>
        ) : (
          <Text className="text-[11px] text-faint">Swipe for more weeks</Text>
        )}
      </View>

      <View
        className="overflow-hidden"
        onLayout={(e) => setWidth(e.nativeEvent.layout.width)}
        {...panResponder.panHandlers}
      >
        <Animated.View
          style={{
            flexDirection: "row",
            width: width ? width * 3 : "300%",
            transform: [{ translateX }]
          }}
        >
          {panels.map((panel) => (
            <View
              key={panel.offset}
              style={{ width: width || undefined }}
              className="flex-row gap-1"
            >
              {panel.days.map((day, i) => {
                const key = toDateKey(day);
                const isToday = key === todayKey;
                return (
                  <Pressable
                    key={`${panel.offset}-${key}`}
                    accessibilityRole="button"
                    accessibilityLabel={day.toDateString()}
                    onPress={() => {
                      tapHaptic();
                      onSelectDay(day);
                    }}
                    className={
                      isToday
                        ? "flex-1 items-center rounded-lg border border-[#22c55e]/35 bg-[#22c55e]/10 px-0.5 py-1.5"
                        : "flex-1 items-center rounded-lg border border-transparent px-0.5 py-1.5"
                    }
                  >
                    <Text
                      className={
                        isToday
                          ? "font-sans-bold text-[10px] tracking-wide text-[#22c55e]"
                          : "font-sans-semibold text-[10px] tracking-wide text-faint"
                      }
                    >
                      {DAY_LABELS[i]}
                    </Text>
                    <Text
                      className={
                        isToday
                          ? "mt-0.5 font-sans-bold text-[13px] text-[#22c55e]"
                          : "mt-0.5 font-sans-bold text-[13px] text-foreground"
                      }
                    >
                      {day.getDate()}
                    </Text>
                    <View
                      className={
                        plannedKeys.has(key)
                          ? "mt-1.5 h-1.5 w-1.5 rounded-full bg-[#22c55e]"
                          : "mt-1.5 h-1.5 w-1.5 rounded-full bg-gap-dot"
                      }
                    />
                  </Pressable>
                );
              })}
            </View>
          ))}
        </Animated.View>
      </View>
    </View>
  );
}

// src/components/HomeWeekStrip.vue
<script setup lang="ts">
import { addDays, startOfDay, startOfWeekMonday, toDateKey } from "@/lib/media";
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from "vue";

const props = defineProps<{
  plannedKeys: Set<string>;
}>();

const emit = defineEmits<{
  selectDay: [date: Date];
  /** Fired with the center week, plus a range covering prev/current/next for dots. */
  weekChange: [weekStart: Date, weekDays: Date[], rangeStart: Date, rangeEnd: Date];
}>();

const DAY_LABELS = ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"];
const SWIPE_THRESHOLD_RATIO = 0.22;
const SWIPE_VELOCITY = 0.45; // px/ms
const SNAP_MS = 280;

const today = startOfDay();
const thisWeekStart = startOfWeekMonday(today);

/** 0 = this week; negative = past; positive = future */
const weekOffset = ref(0);

const viewportEl = ref<HTMLElement | null>(null);
const trackEl = ref<HTMLElement | null>(null);
const viewportWidth = ref(0);

/** Pixel offset of the track. Resting position centers the middle (current) week. */
const translateX = ref(0);
const animating = ref(false);
const dragging = ref(false);

let startX = 0;
let startY = 0;
let startTranslate = 0;
let startTime = 0;
let axis: "x" | "y" | null = null;
let activePointerId: number | null = null;
let pressedDayKey: string | null = null;
let resizeObserver: ResizeObserver | null = null;

const centerWeekStart = computed(() => addDays(thisWeekStart, weekOffset.value * 7));

const panels = computed(() => {
  const center = weekOffset.value;
  return [
    { offset: center - 1, days: daysForOffset(center - 1) },
    { offset: center, days: daysForOffset(center) },
    { offset: center + 1, days: daysForOffset(center + 1) }
  ];
});

const weekLabel = computed(() => labelForOffset(weekOffset.value));

const restingTranslate = computed(() => -viewportWidth.value);

const trackStyle = computed(() => ({
  width: viewportWidth.value ? `${viewportWidth.value * 3}px` : "300%",
  transform: `translate3d(${translateX.value}px, 0, 0)`,
  transition: animating.value ? `transform ${SNAP_MS}ms cubic-bezier(0.22, 1, 0.36, 1)` : "none"
}));

const panelStyle = computed(() => ({
  width: viewportWidth.value ? `${viewportWidth.value}px` : "33.333%"
}));

watch(
  centerWeekStart,
  (start) => {
    const days = daysForOffset(weekOffset.value);
    const rangeStart = addDays(start, -7);
    const rangeEnd = addDays(start, 13);
    emit("weekChange", start, days, rangeStart, rangeEnd);
  },
  { immediate: true }
);

function daysForOffset(offset: number): Date[] {
  const start = addDays(thisWeekStart, offset * 7);
  return Array.from({ length: 7 }, (_, i) => addDays(start, i));
}

function labelForOffset(offset: number): string {
  if (offset === 0) return "This week";
  if (offset === -1) return "Last week";
  if (offset === 1) return "Next week";
  const start = addDays(thisWeekStart, offset * 7);
  const end = addDays(start, 6);
  const opts: Intl.DateTimeFormatOptions = { month: "short", day: "numeric" };
  return `${start.toLocaleDateString(undefined, opts)} – ${end.toLocaleDateString(undefined, opts)}`;
}

function measure() {
  viewportWidth.value = viewportEl.value?.clientWidth ?? 0;
  if (!dragging.value && !animating.value) {
    translateX.value = restingTranslate.value;
  }
}

function dayFromKey(key: string | null): Date | null {
  if (!key) return null;
  for (const panel of panels.value) {
    const hit = panel.days.find((d) => toDateKey(d) === key);
    if (hit) return hit;
  }
  return null;
}

async function snapTo(delta: -1 | 0 | 1) {
  if (!viewportWidth.value) return;

  if (delta === 0) {
    animating.value = true;
    translateX.value = restingTranslate.value;
    window.setTimeout(() => {
      animating.value = false;
    }, SNAP_MS + 20);
    return;
  }

  animating.value = true;
  // Prev panel is at 0, current at -width, next at -2*width
  translateX.value = delta < 0 ? 0 : -viewportWidth.value * 2;

  await new Promise<void>((resolve) => {
    window.setTimeout(resolve, SNAP_MS + 20);
  });

  // Recenter without animation: shift the logical week, rebuild panels, reset translate.
  animating.value = false;
  weekOffset.value += delta;
  await nextTick();
  translateX.value = restingTranslate.value;
}

function goToThisWeek() {
  if (weekOffset.value === 0) return;
  const delta = weekOffset.value > 0 ? -1 : 1;
  // If we're adjacent, animate; otherwise jump.
  if (Math.abs(weekOffset.value) === 1) {
    void snapTo(delta as -1 | 1);
  } else {
    animating.value = false;
    weekOffset.value = 0;
    translateX.value = restingTranslate.value;
  }
}

function onPointerDown(event: PointerEvent) {
  if (event.button !== 0 || animating.value) return;
  dragging.value = true;
  axis = null;
  activePointerId = event.pointerId;
  startX = event.clientX;
  startY = event.clientY;
  startTranslate = translateX.value;
  startTime = performance.now();

  const target = event.target;
  const el = target instanceof Element ? target.closest("[data-day-key]") : null;
  pressedDayKey = el?.getAttribute("data-day-key") ?? null;

  viewportEl.value?.setPointerCapture?.(event.pointerId);
}

function onPointerMove(event: PointerEvent) {
  if (!dragging.value) return;
  if (activePointerId !== null && event.pointerId !== activePointerId) return;

  const dx = event.clientX - startX;
  const dy = event.clientY - startY;

  if (axis === null) {
    if (Math.abs(dx) < 8 && Math.abs(dy) < 8) return;
    axis = Math.abs(dx) > Math.abs(dy) ? "x" : "y";
    if (axis === "y") {
      cancelDrag();
      return;
    }
  }

  if (axis !== "x") return;
  event.preventDefault();
  translateX.value = startTranslate + dx;
}

function finishDrag() {
  if (!dragging.value) return;
  const dx = translateX.value - startTranslate;
  const dt = Math.max(performance.now() - startTime, 1);
  const velocity = dx / dt;
  const key = pressedDayKey;
  const wasHorizontal = axis === "x";

  dragging.value = false;
  activePointerId = null;
  pressedDayKey = null;
  axis = null;

  const width = viewportWidth.value || 1;
  const distanceCommit = Math.abs(dx) >= width * SWIPE_THRESHOLD_RATIO;
  const velocityCommit = Math.abs(velocity) >= SWIPE_VELOCITY;
  const shouldFlip = wasHorizontal && (distanceCommit || velocityCommit);

  if (shouldFlip) {
    void snapTo(dx < 0 ? 1 : -1);
    return;
  }

  // Treat near-stationary releases as day taps, even if axis locked to x from jitter.
  const day = dayFromKey(key);
  if (day && Math.abs(dx) < 12) {
    translateX.value = restingTranslate.value;
    emit("selectDay", day);
    return;
  }

  if (wasHorizontal) {
    void snapTo(0);
    return;
  }

  translateX.value = restingTranslate.value;
  if (day) emit("selectDay", day);
}

function cancelDrag() {
  dragging.value = false;
  activePointerId = null;
  axis = null;
  pressedDayKey = null;
  translateX.value = restingTranslate.value;
}

function onPointerUp(event: PointerEvent) {
  if (activePointerId !== null && event.pointerId !== activePointerId) return;
  finishDrag();
}

onMounted(() => {
  measure();
  resizeObserver = new ResizeObserver(() => measure());
  if (viewportEl.value) resizeObserver.observe(viewportEl.value);
});

onBeforeUnmount(() => {
  resizeObserver?.disconnect();
});

defineExpose({
  weekStart: centerWeekStart,
  weekOffset,
  goToThisWeek
});
</script>

<template>
  <div class="select-none">
    <div class="mb-2 flex items-center justify-between gap-2">
      <p class="text-xs font-semibold text-muted-foreground">{{ weekLabel }}</p>
      <button
        v-if="weekOffset !== 0"
        type="button"
        class="text-[11.5px] font-semibold text-[#22c55e] transition-opacity active:opacity-70"
        @click="goToThisWeek"
      >
        Jump to this week
      </button>
      <p v-else class="text-[11px] text-faint">Swipe for more weeks</p>
    </div>

    <div
      ref="viewportEl"
      class="touch-pan-y overflow-hidden"
      @pointerdown="onPointerDown"
      @pointermove="onPointerMove"
      @pointerup="onPointerUp"
      @pointercancel="cancelDrag"
      @lostpointercapture="finishDrag"
    >
      <div ref="trackEl" class="flex will-change-transform" :style="trackStyle">
        <div
          v-for="panel in panels"
          :key="panel.offset"
          class="grid shrink-0 grid-cols-7 gap-1 px-0"
          :style="panelStyle"
        >
          <div
            v-for="(day, i) in panel.days"
            :key="`${panel.offset}-${toDateKey(day)}`"
            role="button"
            tabindex="0"
            :data-day-key="toDateKey(day)"
            class="cursor-pointer rounded-lg px-0.5 py-1.5 text-center transition-colors"
            :class="
              toDateKey(day) === toDateKey(today)
                ? 'border border-[rgba(34,197,94,0.35)] bg-[rgba(34,197,94,0.12)]'
                : 'border border-transparent'
            "
            @keydown.enter.prevent="emit('selectDay', day)"
            @keydown.space.prevent="emit('selectDay', day)"
          >
            <div
              class="text-[10px] font-semibold tracking-wide"
              :class="
                toDateKey(day) === toDateKey(today) ? 'font-bold text-[#22c55e]' : 'text-faint'
              "
            >
              {{ DAY_LABELS[i] }}
            </div>
            <div
              class="mt-0.5 text-[13px] font-bold leading-none tabular-nums"
              :class="toDateKey(day) === toDateKey(today) ? 'text-[#22c55e]' : 'text-foreground'"
            >
              {{ day.getDate() }}
            </div>
            <div
              class="mx-auto mt-1.5 size-1.5 rounded-full"
              :class="plannedKeys.has(toDateKey(day)) ? 'bg-[#22c55e]' : 'bg-[#3f3f46]'"
            />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>
