// mobile/src/components/RecipeCard.tsx
import { formatPrepTime } from "@/lib/dates";
import { colors } from "@/lib/colors";
import { tapHaptic } from "@/lib/haptics";
import { mediaSource } from "@/lib/media";
import type { RecipeCard as RecipeCardType } from "@/types";
import { Image } from "expo-image";
import { useRouter } from "expo-router";
import { Clock } from "lucide-react-native";
import { Pressable, View } from "react-native";
import { Skeleton } from "./ui/skeleton";
import { Text } from "./ui/text";

/** List card: cover thumb, name, description, prep time. */
export function RecipeCard({ recipe }: { recipe: RecipeCardType }) {
  const router = useRouter();

  return (
    <Pressable
      accessibilityRole="button"
      onPress={() => {
        tapHaptic();
        router.push(`/recipes/${recipe.id}`);
      }}
      className="flex-row gap-3 rounded-xl border border-border bg-card p-3 active:opacity-80"
    >
      <Image
        source={mediaSource(recipe.cover_image?.url)}
        style={{ width: 96, height: 96, borderRadius: 12, backgroundColor: colors.muted }}
        contentFit="cover"
        transition={150}
      />
      <View className="min-w-0 flex-1 justify-center">
        <Text className="font-sans-semibold text-base" numberOfLines={1}>
          {recipe.name}
        </Text>
        {recipe.description ? (
          <Text className="mt-0.5 text-sm leading-5 text-muted-foreground" numberOfLines={2}>
            {recipe.description}
          </Text>
        ) : null}
        {recipe.prep_time ? (
          <View className="mt-1.5 flex-row items-center gap-1.5">
            <Clock size={13} color={colors.mutedForeground} />
            <Text className="text-xs text-muted-foreground">
              {formatPrepTime(recipe.prep_time)}
            </Text>
          </View>
        ) : null}
      </View>
    </Pressable>
  );
}

export function RecipeCardSkeleton() {
  return (
    <View className="flex-row gap-3 rounded-xl border border-border bg-card p-3">
      <Skeleton className="h-24 w-24 rounded-lg" />
      <View className="flex-1 justify-center gap-2">
        <Skeleton className="h-4 w-2/3" />
        <Skeleton className="h-3 w-full" />
        <Skeleton className="h-3 w-1/3" />
      </View>
    </View>
  );
}

// src/components/RecipeCard.vue
<script setup lang="ts">
import { formatPrepTime, mediaUrl } from "@/lib/media";
import { cn } from "@/lib/utils";
import { paths } from "@/sitemap";
import type { RecipeCard } from "@/types";
import { Clock } from "@lucide/vue";
import { computed } from "vue";
import { useRoute, useRouter } from "vue-router";

const props = withDefaults(
  defineProps<{
    recipe: RecipeCard & {
      created_by?: { display_name: string };
    };
    size?: "sm" | "md";
    mode?: "default" | "public";
  }>(),
  { size: "md", mode: "default" }
);

const router = useRouter();
const route = useRoute();

const image = computed(() => mediaUrl(props.recipe.cover_image?.url));
const prep = computed(() => formatPrepTime(props.recipe.prep_time));

function open() {
  router.push({
    path: paths.recipeDetail(props.recipe.id),
    query: { returnUrl: route.fullPath }
  });
}
</script>

<template>
  <button
    type="button"
    :class="
      cn(
        'flex w-full items-stretch gap-3 overflow-hidden rounded-xl border border-border bg-card text-left transition-opacity active:opacity-80',
        size === 'sm' ? 'p-2' : 'p-3'
      )
    "
    @click="open"
  >
    <img
      :src="image"
      :alt="recipe.name"
      :class="cn('shrink-0 rounded-lg object-cover', size === 'sm' ? 'size-14' : 'size-20')"
    />
    <div class="min-w-0 flex-1 py-0.5">
      <p :class="cn('truncate font-semibold', size === 'sm' ? 'text-sm' : 'text-[15px]')">
        {{ recipe.name }}
      </p>
      <p
        v-if="mode === 'public' && recipe.created_by"
        class="mt-0.5 truncate text-xs text-muted-foreground"
      >
        {{ recipe.created_by.display_name }}
      </p>
      <p v-else-if="recipe.description" class="mt-0.5 line-clamp-2 text-xs text-muted-foreground">
        {{ recipe.description }}
      </p>
      <p
        v-if="mode === 'default' && prep"
        class="mt-1.5 flex items-center gap-1 text-[11px] text-faint"
      >
        <Clock class="size-3" />
        {{ prep }}
      </p>
    </div>
  </button>
</template>
