// mobile/src/components/SwipeRow.tsx
import { Text } from "@/components/ui/text";
import { colors } from "@/lib/colors";
import { Eye, Trash2 } from "lucide-react-native";
import { useEffect, useRef, useState, type ReactNode } from "react";
import { Animated, PanResponder, Pressable, View } from "react-native";

const DEFAULT_ACTION_WIDTH = 128;
const DISMISS_THRESHOLD = 72;
const OPEN_THRESHOLD = 40;
const MAX_RIGHT = 180;

function clamp(value: number, min: number, max: number) {
  return Math.min(max, Math.max(min, value));
}

/**
 * Swipeable list row (grocery + planner). Drag right past the threshold to
 * fire onDismiss (when enabled), drag left to reveal action buttons.
 */
export function SwipeRow({
  children,
  onDismiss,
  onDelete,
  onView,
  actionWidth = DEFAULT_ACTION_WIDTH,
  canSwipeRight = true,
  dismissLabel = "Dismiss",
  deleteLabel = "Remove from list"
}: {
  children: ReactNode;
  onDismiss?: () => void;
  onDelete: () => void;
  onView?: () => void;
  actionWidth?: number;
  canSwipeRight?: boolean;
  dismissLabel?: string;
  deleteLabel?: string;
}) {
  const allowRight = Boolean(canSwipeRight && onDismiss);
  const trayWidth = onView ? actionWidth : Math.min(actionWidth, 72);
  const [offset] = useState(() => new Animated.Value(0));
  const settledOffset = useRef(0);
  const [open, setOpen] = useState(false);
  const openRef = useRef(false);

  const actions = useRef({ onDismiss, onDelete, onView, allowRight, trayWidth });
  useEffect(() => {
    actions.current = { onDismiss, onDelete, onView, allowRight, trayWidth };
  }, [onDismiss, onDelete, onView, allowRight, trayWidth]);

  const setOpenState = (value: boolean) => {
    openRef.current = value;
    setOpen(value);
  };

  const settleTo = (value: number) => {
    settledOffset.current = value;
    Animated.timing(offset, { toValue: value, duration: 180, useNativeDriver: true }).start();
  };

  const close = () => {
    setOpenState(false);
    settleTo(0);
  };

  // eslint-disable-next-line react-hooks/refs
  const [panResponder] = useState(() =>
    PanResponder.create({
      onMoveShouldSetPanResponder: (_e, g) =>
        Math.abs(g.dx) > 8 && Math.abs(g.dx) > Math.abs(g.dy) * 1.4,
      onPanResponderMove: (_e, g) => {
        const { allowRight: right, trayWidth: tray } = actions.current;
        offset.setValue(clamp(settledOffset.current + g.dx, -tray, right ? MAX_RIGHT : 0));
      },
      onPanResponderRelease: (_e, g) => {
        const { allowRight: right, trayWidth: tray, onDismiss: dismiss } = actions.current;
        const finalOffset = clamp(settledOffset.current + g.dx, -tray, right ? MAX_RIGHT : 0);
        const settle = (value: number) => {
          openRef.current = value !== 0;
          setOpen(value !== 0);
          settledOffset.current = value;
          Animated.timing(offset, { toValue: value, duration: 180, useNativeDriver: true }).start();
        };
        if (right && finalOffset >= DISMISS_THRESHOLD) {
          settle(0);
          dismiss?.();
        } else if (finalOffset <= -OPEN_THRESHOLD) {
          settle(-tray);
        } else {
          settle(0);
        }
      },
      onPanResponderTerminate: () => {
        const tray = actions.current.trayWidth;
        const value = openRef.current ? -tray : 0;
        settledOffset.current = value;
        Animated.timing(offset, { toValue: value, duration: 180, useNativeDriver: true }).start();
      }
    })
  );

  return (
    <View className="relative overflow-hidden">
      {allowRight ? (
        <View className="absolute inset-y-0 left-0 w-28 justify-center bg-[rgba(34,197,94,0.22)] pl-4">
          <Text className="font-sans-semibold text-xs text-[#4ade80]">{dismissLabel}</Text>
        </View>
      ) : null}

      <View className="absolute inset-y-0 right-0 flex-row" style={{ width: trayWidth }}>
        {onView ? (
          <Pressable
            accessibilityRole="button"
            accessibilityLabel="View recipe"
            onPress={() => {
              close();
              onView();
            }}
            className="flex-1 items-center justify-center bg-[#3f463f] active:opacity-80"
          >
            <Eye size={20} color={colors.foreground} strokeWidth={2} />
          </Pressable>
        ) : null}
        <Pressable
          accessibilityRole="button"
          accessibilityLabel={deleteLabel}
          onPress={() => {
            close();
            onDelete();
          }}
          className="flex-1 items-center justify-center bg-[#dc2626] active:opacity-80"
        >
          <Trash2 size={20} color={colors.foreground} strokeWidth={2} />
        </Pressable>
      </View>

      <Animated.View
        {...panResponder.panHandlers}
        style={{ transform: [{ translateX: offset }] }}
        className="bg-card"
      >
        <Pressable disabled={!open} onPress={close} accessibilityLabel="Close actions">
          {children}
        </Pressable>
      </Animated.View>
    </View>
  );
}

// src/components/grocery/SwipeRow.vue
<script setup lang="ts">
import { cn } from "@/lib/utils";
import { Eye, Trash2 } from "@lucide/vue";
import { computed, ref } from "vue";

const props = withDefaults(
  defineProps<{
    disabled?: boolean;
    class?: string;
  }>(),
  { disabled: false, class: undefined }
);

const emit = defineEmits<{
  dismiss: [];
  delete: [];
  view: [];
}>();

const ACTION_WIDTH = 128;
const DISMISS_THRESHOLD = 96;
const OPEN_THRESHOLD = 48;

const offset = ref(0);
const dragging = ref(false);
const openLeft = ref(false);

let startX = 0;
let startY = 0;
let startOffset = 0;
let axis: "x" | "y" | null = null;

const style = computed(() => ({
  transform: `translate3d(${offset.value}px, 0, 0)`,
  transition: dragging.value ? "none" : "transform 180ms ease-out"
}));

function clamp(value: number, min: number, max: number) {
  return Math.min(max, Math.max(min, value));
}

function onPointerDown(event: PointerEvent) {
  if (props.disabled) return;
  dragging.value = true;
  axis = null;
  startX = event.clientX;
  startY = event.clientY;
  startOffset = offset.value;
  (event.currentTarget as HTMLElement).setPointerCapture?.(event.pointerId);
}

function onPointerMove(event: PointerEvent) {
  if (!dragging.value || props.disabled) return;
  const dx = event.clientX - startX;
  const dy = event.clientY - startY;

  if (axis === null) {
    if (Math.abs(dx) < 6 && Math.abs(dy) < 6) return;
    axis = Math.abs(dx) > Math.abs(dy) ? "x" : "y";
    if (axis === "y") {
      dragging.value = false;
      return;
    }
  }

  event.preventDefault();
  // Left swipe → negative offset (reveal actions). Right swipe → positive (dismiss).
  offset.value = clamp(startOffset + dx, -ACTION_WIDTH, 160);
}

function onPointerUp() {
  if (!dragging.value && axis !== "x") {
    dragging.value = false;
    axis = null;
    return;
  }
  dragging.value = false;

  if (offset.value >= DISMISS_THRESHOLD) {
    offset.value = 0;
    openLeft.value = false;
    emit("dismiss");
  } else if (offset.value <= -OPEN_THRESHOLD) {
    offset.value = -ACTION_WIDTH;
    openLeft.value = true;
  } else {
    offset.value = 0;
    openLeft.value = false;
  }
  axis = null;
}

function close() {
  offset.value = 0;
  openLeft.value = false;
}

function onDelete() {
  close();
  emit("delete");
}

function onView() {
  close();
  emit("view");
}

defineExpose({ close });
</script>

<template>
  <div class="relative overflow-hidden rounded-xl">
    <!-- Right-swipe dismiss hint -->
    <div
      class="absolute inset-y-0 left-0 flex w-28 items-center justify-start bg-[rgba(34,197,94,0.2)] pl-4"
      aria-hidden="true"
    >
      <span class="text-xs font-semibold text-[#4ade80]">Dismiss</span>
    </div>

    <!-- Left-swipe actions -->
    <div class="absolute inset-y-0 right-0 flex w-32 items-stretch" aria-hidden="true">
      <button
        type="button"
        class="flex flex-1 items-center justify-center bg-[#27272a] text-[#fafafa] transition-opacity active:opacity-80"
        tabindex="-1"
        @click="onView"
      >
        <Eye class="size-5" :stroke-width="2" />
      </button>
      <button
        type="button"
        class="flex flex-1 items-center justify-center bg-[#dc2626] text-white transition-opacity active:opacity-80"
        tabindex="-1"
        @click="onDelete"
      >
        <Trash2 class="size-5" :stroke-width="2" />
      </button>
    </div>

    <div
      :class="cn('relative z-10 touch-pan-y bg-card select-none', props.class)"
      :style="style"
      @pointerdown="onPointerDown"
      @pointermove="onPointerMove"
      @pointerup="onPointerUp"
      @pointercancel="onPointerUp"
    >
      <slot :open="openLeft" />
    </div>
  </div>
</template>
